AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thumbnail-app

  Sample SAM Template for thumbnail-app

Parameters:
  StartBucketName:
    Type: String
    Description: 'S3 bucket name to retrive initial photo.'
    Default: "thumbnail-1488"

  EndBucketName:
    Type: String
    Description: 'S3 bucket name to save photo thumbnail.'
    Default: "thumbnail-228"

Resources:
  S3StartBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref StartBucketName

  S3EndBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref EndBucketName

  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: thumbnail-lambda-function
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3StartBucket
            Events: s3:ObjectCreated:*
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub 'arn:aws:s3:::${StartBucketName}/*'
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${EndBucketName}/*'
      Runtime: python3.8
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          EndBucketName: !Ref EndBucketName

  CleanerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chache-cleaner-lambda-function
      CodeUri: src/fs/cleaner
      Handler: app.lambda_handler
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: chache cleaner schedule
            Description: chache cleaner schedule
            Enabled: True
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::${S3StartBucket}/*'
      Runtime: python3.8
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          AppBucketName: !Ref S3StartBucket